"""Generate the title pages (xml/Custom_1130..1134) and their per-page variables.

Run from the skin folder:  python3 tools/gen_details.py

Why five windows: Kodi 21 always closes a custom window on Back (a control's <onback>
runs but can't stop it). Giving each level of "title -> recommended title -> ..." its own
window lets Kodi's normal window history do the Back navigation. extras/details.py picks
the next page and fills Skin.String(DetailTypeN) / Skin.String(DetailIDN).
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PAGES = 5

TEMPLATE = os.path.join(ROOT, 'tools', 'details_template.xml')

VARIABLES = '''
	<!-- ===== Title page {n} (window 113{n}) ===== -->
	<expression name="ATV_DetailIsTV{n}">String.IsEqual(Skin.String(DetailType{n}),tv)</expression>
	<variable name="ATV_DetailPath{n}">
		<value>plugin://plugin.video.themoviedb.helper/?info=details&amp;tmdb_type=$INFO[Skin.String(DetailType{n})]&amp;tmdb_id=$INFO[Skin.String(DetailID{n})]</value>
	</variable>
	<!-- Titles sharing all of this title's genres (minus the title itself). TV genres such as
	     "Action & Adventure" would break the URL, so those shows use TMDb's similar list. -->
	<variable name="ATV_DetailGenrePath{n}">
		<value condition="$EXP[ATV_DetailIsTV{n}] + String.Contains(Container(9500).ListItem.Genre,&amp;)">plugin://plugin.video.themoviedb.helper/?info=similar&amp;tmdb_type=tv&amp;tmdb_id=$INFO[Skin.String(DetailID{n})]</value>
		<value condition="!String.IsEmpty(Container(9500).ListItem.Genre)">plugin://plugin.video.themoviedb.helper/?info=discover&amp;tmdb_type=$INFO[Skin.String(DetailType{n})]&amp;with_genres=$INFO[Container(9500).ListItem.Genre]&amp;sort_by=popularity.desc&amp;exclude_key=tmdb_id&amp;exclude_value=$INFO[Skin.String(DetailID{n})]&amp;exclude_operator=eq</value>
	</variable>
	<variable name="ATV_DetailMeta{n}">
		<value condition="$EXP[ATV_DetailIsTV{n}]">TV Show$INFO[Container(9500).ListItem.Year,  ·  ]$INFO[Container(9500).ListItem.Genre,  ·  ]$INFO[Container(9500).ListItem.MPAA,  ·  ]$INFO[Container(9500).ListItem.Rating,  ·  ★ ]</value>
		<value>Movie$INFO[Container(9500).ListItem.Year,  ·  ]$INFO[Container(9500).ListItem.Genre,  ·  ]$INFO[Container(9500).ListItem.Duration(mins),  ·  , min]$INFO[Container(9500).ListItem.MPAA,  ·  ]$INFO[Container(9500).ListItem.Rating,  ·  ★ ]</value>
	</variable>
	<variable name="ATV_DetailPlayLabel{n}">
		<value condition="$EXP[ATV_DetailIsTV{n}] + Integer.IsGreater(Container(9610).ListItem.Season,0)">Play S$INFO[Container(9610).ListItem.Season] E1</value>
		<value condition="$EXP[ATV_DetailIsTV{n}]">Play S1 E1</value>
		<value>Play</value>
	</variable>
'''


def main():
    with open(TEMPLATE) as f:
        template = f.read()
    for n in range(PAGES):
        with open(os.path.join(ROOT, 'xml', f'Custom_113{n}_Details.xml'), 'w') as f:
            f.write(template.replace('§', str(n)))
    with open(os.path.join(ROOT, 'xml', 'Includes_ATV_Details.xml'), 'w') as f:
        f.write('<?xml version="1.0" encoding="UTF-8"?>\n'
                '<!-- GENERATED by tools/gen_details.py - per-page variables for the title pages -->\n'
                '<includes>' + ''.join(VARIABLES.format(n=n) for n in range(PAGES)) + '</includes>\n')
    print(f'wrote {PAGES} title pages + Includes_ATV_Details.xml')


if __name__ == '__main__':
    main()
