"""Generate xml/Includes_ATV_Rank.xml - the numbered "Top 10" row.

Run from the skin folder:  python3 tools/gen_rank.py

Kodi gives a row's layout no way to know an item's position, and TMDb Helper doesn't tag
items with a rank, so a normal container cannot print "1, 2, 3...". Instead the row is ten
fixed tiles inside a horizontal grouplist (which still scrolls with focus), each bound to
one absolute position of a hidden data list via Container(x).ListItemAbsolute(n).

Usage from a window:

    <include content="ATV_RankRow">
        <param name="id" value="51" />            <!-- the grouplist (focus target) -->
        <param name="idbase" value="61" />        <!-- tiles get ids 610..619, buttons 6101..6191 -->
        <param name="data" value="6051" />        <!-- hidden list holding the items -->
        <param name="top" value="1240" />
        <param name="label" value="Top 10 Movies Today" />
        <param name="content" value="plugin://..." />
        <param name="onup" value="50" />
        <param name="ondown" value="52" />
    </include>
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
COUNT = 10
SLOT = 292          # pitch of one tile
POSTER_LEFT = 108   # poster overlaps the numeral, as on Netflix
POSTER_W, POSTER_H = 180, 270


def tile(index):  # noqa: C901
    """One numbered tile: giant numeral, poster over it, lift on focus.

    The grouplist lays the tiles out itself, so each tile only declares its size.
    """
    nav = ''
    if index:
        nav += f'<onleft>$PARAM[idbase]{index - 1}1</onleft>'
    if index < COUNT - 1:
        nav += f'<onright>$PARAM[idbase]{index + 1}1</onright>'
    nav += '<onup>$PARAM[onup]</onup><ondown>$PARAM[ondown]</ondown>'
    return f'''
					<control type="group" id="$PARAM[idbase]{index}">
						<width>{SLOT}</width><height>340</height>
						<animation effect="zoom" start="100" end="108" center="{POSTER_LEFT + POSTER_W // 2},175" time="220" tween="cubic" easing="out" condition="Control.HasFocus($PARAM[id]) + ControlGroup($PARAM[id]).HasFocus({index + 1})">Conditional</animation>
						<control type="label">
							<left>0</left><top>20</top><width>240</width><height>300</height>
							<!-- $NUMBER[] because Kodi reads a bare number as a translated-string id -->
							<label>$NUMBER[{index + 1}]</label>
							<font>atv_rank</font><textcolor>59FFFFFF</textcolor>
							<align>left</align><aligny>bottom</aligny>
						</control>
						<control type="image">
							<left>{POSTER_LEFT - 24}</left><top>16</top><width>{POSTER_W + 48}</width><height>{POSTER_H + 48}</height>
							<texture border="64">atv/shadow.png</texture>
							<visible>Control.HasFocus($PARAM[id]) + ControlGroup($PARAM[id]).HasFocus({index + 1})</visible>
						</control>
						<control type="image">
							<left>{POSTER_LEFT}</left><top>40</top><width>{POSTER_W}</width><height>{POSTER_H}</height>
							<texture colordiffuse="FF1C1C1E" diffuse="atv/mask_poster.png">white.png</texture>
						</control>
						<control type="image">
							<left>{POSTER_LEFT}</left><top>40</top><width>{POSTER_W}</width><height>{POSTER_H}</height>
							<aspectratio scalediffuse="false">scale</aspectratio>
							<texture background="true" diffuse="atv/mask_poster.png">$INFO[Container($PARAM[data]).ListItemAbsolute({index}).Art(poster)]</texture>
						</control>
						<control type="button" id="$PARAM[idbase]{index}1">
							<left>{POSTER_LEFT}</left><top>40</top><width>{POSTER_W}</width><height>{POSTER_H}</height>
							<label></label><font></font>
							<texturefocus />
							<texturenofocus />
							<pulseonselect>false</pulseonselect>
							<onclick>RunScript(special://skin/extras/details.py,open,$PARAM[data],{index})</onclick>
							{nav}
						</control>
					</control>'''


def main():
    tiles = ''.join(tile(i) for i in range(COUNT))
    xml = f'''<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by tools/gen_rank.py - edit the generator, not this file -->
<includes>
	<include name="ATV_RankRow">
		<param name="id" />
		<param name="idbase" />
		<param name="data" />
		<param name="top" />
		<param name="label" />
		<param name="content" />
		<param name="onup" />
		<param name="ondown">noop</param>
		<param name="onback">SetFocus(8001)</param>
		<definition>
			<control type="group">
				<top>$PARAM[top]</top>
				<control type="label">
					<left>90</left><top>0</top><width>1400</width><height>44</height>
					<label>$PARAM[label]</label>
					<font>atv_row</font>
					<textcolor>FFFFFFFF</textcolor>
				</control>
				<!-- Hidden list: holds the ten items the tiles read by position -->
				<control type="list" id="$PARAM[data]">
					<left>0</left><top>1078</top><width>10</width><height>2</height>
					<itemlayout width="1" height="1" />
					<focusedlayout width="1" height="1" />
					<content limit="{COUNT}">$PARAM[content]</content>
				</control>
				<control type="grouplist" id="$PARAM[id]">
					<left>82</left><top>40</top><width>1760</width><height>340</height>
					<orientation>horizontal</orientation>
					<itemgap>0</itemgap>
					<scrolltime tween="sine" easing="inout">380</scrolltime>
					<onup>$PARAM[onup]</onup>
					<ondown>$PARAM[ondown]</ondown>
					<onback>$PARAM[onback]</onback>{tiles}
				</control>
			</control>
		</definition>
	</include>
</includes>
'''
    with open(os.path.join(ROOT, 'xml', 'Includes_ATV_Rank.xml'), 'w') as f:
        f.write(xml)
    print(f'wrote Includes_ATV_Rank.xml ({COUNT} tiles)')


if __name__ == '__main__':
    main()
